dist: Xenial
language: python
python: "3.7"
before_install:
  - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
  - sudo add-apt-repository -y 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial main'
  - sudo apt update
  - sudo apt install -y clang clang-format
script:
  - clang-format --version
  - clang-format-9 --version
