dist: xenial
language: python
python: "3.7"
addons:
  apt:
    update: true
    sources:
    - sourceline: llvm-toolchain-xenial-9
      key_url: https://apt.llvm.org/llvm-snapshot.gpg.key
    packages:
    - clang-format-9.0
script:
  - clang-format --version
  - clang-format-9 --version
