dist: Xenial
language: python
python: 
  - "3.6"
before_install:
  - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
  - sudo add-apt-repository -y 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial main'
  - sudo apt update
install:
  - sudo apt install -y clang-format-9
  - npm install -g markdownlint-cli
script:
  - clang-format-9 --version
  - markdownlint --version
  - python3.6 --version
