addons:
  apt:
    sources:
      - llvm-toolchain-trusty
      - key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - libllvm9
      - libstdc++6
      - clang-format-9
script:
  - clang-format --version
