dist: Xenial
language: node_js
node_js:
  - "6"
before_install:
  - sudo add-apt-repository ppa:jonathonf/python-3.6
  - sudo apt update
install:
  - sudo apt-get install python3.6
script:
  - python3 --version
  - ls /usr/bin/python*
