dist: Xenial
addons:
  apt:
    sources:
      - llvm-toolchain-trusty
      - key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
before_install:
  - sudo apt-get install -y clang-format-9
script:
  - clang-format --version
