dist: Xenial
language: python
python: "3.7"
addons:
  apt:
    sources:
    - llvm-toolchain-xenial-9
    - key_url: https://apt.llvm.org/llvm-snapshot.gpg.key
    packages: clang-format-9
    update: true
script:
  - clang-format --version
  - clang-format-9 --version
